/*
 * Multiverse Mages — known-answer vectors for the simulation core's PRNG.
 * Copyright (C) 2026 Ann Kelner
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version. See the LICENSE file at the repository root, or
 * <https://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

/**
 * These vectors are a tripwire. Every committed Monte Carlo balance baseline,
 * every golden replay fixture, and every recorded PvP match is a claim about
 * the exact sequence this generator produces. A refactor that changes the
 * sequence — a "harmless" reordering of the output function, a different
 * mixing constant — would invalidate all of them silently. It fails here
 * instead, loudly, in the change that caused it.
 *
 * The vectors are layered on purpose, so a failure says *which* layer moved:
 *
 * 1. `pcg32 reference conformance` — external truth. Not generated by this
 *    implementation; taken from the pcg32-demo sample output published at
 *    <https://www.pcg-random.org/using-pcg-c-basic.html>. If this fails, the
 *    64-bit limb arithmetic or the XSH-RR output function is wrong.
 * 2. `raw generator vector` — frozen from this implementation. If this fails
 *    but the reference conformance passes, `streamFromWords` changed.
 * 3. `derived stream vector` — frozen from this implementation. If only this
 *    fails, the `(rootSeed, subsystemId, tick)` mixer changed and every
 *    baseline is invalid even though the generator itself is intact.
 */

import { describe, expect, it } from 'vitest';

import type { RngStream } from '@mm/sim-core';
import {
  RNG_STREAM,
  deriveStream,
  nextBounded,
  nextUint32,
  streamFromWords,
} from '@mm/sim-core';

/**
 * Frozen sequence for `streamFromWords(0x12345678, 0x9abcdef0, 0x0f0f0f0f,
 * 0xf0f0f0f0)`. The increment argument is even and is forced odd by the
 * constructor, so this vector also pins that behaviour.
 *
 * Do not regenerate without understanding what it invalidates.
 */
const RAW_VECTOR: readonly string[] = [
  '0x51a297ac',
  '0x39a553a8',
  '0x8a929247',
  '0x3defbef9',
  '0x73ae2f32',
  '0x3c248fc0',
  '0xfa88dc29',
  '0xa697d58b',
];

/**
 * Frozen state words for `deriveStream(0x5eed1234, RNG_STREAM.mageBirth, 7)`,
 * as `[stateHi, stateLo, incHi, incLo]`. Pins the mixer's output directly,
 * before any draw happens.
 *
 * Do not regenerate without understanding what it invalidates.
 */
const DERIVED_STATE_WORDS: readonly string[] = [
  '0xfbb304b1',
  '0xf0974db7',
  '0xc9f8f012',
  '0xa038e9bb',
];

/**
 * Frozen sequence for that same derivation.
 *
 * Do not regenerate without understanding what it invalidates.
 */
const DERIVED_VECTOR: readonly string[] = [
  '0xecce974c',
  '0x2f9caa17',
  '0xd53b692d',
  '0x8bb92f2d',
  '0xbccc2838',
  '0x881a2c70',
  '0x653e00fa',
  '0x5ca11d1c',
];

/**
 * Frozen bounded draws for that same derivation, at a bound of 100 — a bound
 * that does not divide 2^32, so these values also depend on the rejection rule.
 *
 * Do not regenerate without understanding what it invalidates.
 */
const DERIVED_BOUNDED_VECTOR: readonly number[] = [
  24, 11, 57, 61, 48, 88, 98, 20, 92, 94, 99, 12, 62, 42, 71, 96,
];

function hex(value: number): string {
  return `0x${value.toString(16).padStart(8, '0')}`;
}

function takeHex(rng: RngStream, count: number): string[] {
  const values: string[] = [];
  for (let i = 0; i < count; i += 1) {
    values.push(hex(nextUint32(rng)));
  }
  return values;
}

/**
 * Reproduces the reference `pcg32_srandom_r(&rng, initState, initSeq)`:
 * state starts at zero, the increment is `(initSeq << 1) | 1`, one value is
 * drawn and discarded, the initial state is added in, and one more value is
 * drawn and discarded.
 */
function seedLikeReferencePcg32(initState: number, initSeq: number): RngStream {
  const rng = streamFromWords(0, 0, 0, (initSeq * 2 + 1) >>> 0);
  nextUint32(rng);

  const low = (rng.words[1] ?? 0) + initState;
  rng.words[1] = low >>> 0;
  if (low > 0xffffffff) {
    rng.words[0] = ((rng.words[0] ?? 0) + 1) >>> 0;
  }

  nextUint32(rng);
  return rng;
}

describe('pcg32 reference conformance', () => {
  it('matches the published pcg32-demo output for seed 42, sequence 54', () => {
    const rng = seedLikeReferencePcg32(42, 54);
    expect(takeHex(rng, 6)).toEqual([
      '0xa15c02b7',
      '0x7b47f409',
      '0xba1d3330',
      '0x83d2f293',
      '0xbfa4784b',
      '0xcbed606e',
    ]);
  });
});

describe('raw generator vector', () => {
  it('reproduces the frozen sequence from explicit state words', () => {
    const rng = streamFromWords(0x12345678, 0x9abcdef0, 0x0f0f0f0f, 0xf0f0f0f0);
    expect(takeHex(rng, 8)).toEqual(RAW_VECTOR);
  });
});

describe('derived stream vector', () => {
  it('reproduces the frozen sequence for a fixed (rootSeed, subsystemId, tick)', () => {
    const rng = deriveStream(0x5eed1234, RNG_STREAM.mageBirth, 7);
    expect(takeHex(rng, 8)).toEqual(DERIVED_VECTOR);
  });

  it('reproduces the frozen bounded draws for the same derivation', () => {
    const rng = deriveStream(0x5eed1234, RNG_STREAM.mageBirth, 7);
    const rolls: number[] = [];
    for (let i = 0; i < 16; i += 1) {
      rolls.push(nextBounded(rng, 100));
    }
    expect(rolls).toEqual(DERIVED_BOUNDED_VECTOR);
  });

  it('reproduces the frozen initial state words for the same derivation', () => {
    const rng = deriveStream(0x5eed1234, RNG_STREAM.mageBirth, 7);
    expect(Array.from(rng.words).map(hex)).toEqual(DERIVED_STATE_WORDS);
  });
});
